<a href="https://colab.research.google.com/github/swastik175/python_pandas/blob/master/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
df = pd.DataFrame([[1,2,4],[4,6,7],[8,9,3]], columns = ["A","B","C"])
df.head()

   A  B  C
0  1  2  4
1  4  6  7
2  8  9  3

In [25]:
coffee = pd.read_csv("coffee.csv")
coffee['price'] = 4.99
import numpy as np
coffee['new price'] = np.where(coffee['Coffee Type']=="Espresso", 5.99, 4.99)
coffee

          Day Coffee Type  Units Sold  price  new price
0      Monday    Espresso          25   4.99       5.99
1      Monday       Latte          15   4.99       4.99
2     Tuesday    Espresso          30   4.99       5.99
3     Tuesday       Latte          20   4.99       4.99
4   Wednesday    Espresso          35   4.99       5.99
5   Wednesday       Latte          25   4.99       4.99
6    Thursday    Espresso          40   4.99       5.99
7    Thursday       Latte          30   4.99       4.99
8      Friday    Espresso          45   4.99       5.99
9      Friday       Latte          35   4.99       4.99
10   Saturday    Espresso          45   4.99       5.99
11   Saturday       Latte          35   4.99       4.99
12     Sunday    Espresso          45   4.99       5.99
13     Sunday       Latte          35   4.99       4.99

In [14]:
bios = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv')
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [16]:
olympic_results = pd.read_parquet('results.parquet')
olympic_results.tail()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,None,26.0,False,None
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,None,28.0,False,None
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,None
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,None,NaN,False,None
308407,2022.0,Winter,None,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,None,None,24.0,False,None

In [21]:
coffee.loc[5:12, ["Day", "Coffee Type"]]

          Day Coffee Type
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso

Loc is for locating index data values pd.loc([Rows, Columns]) and iLoc is for locating the indices or changing the indices names.

In [23]:
coffee.loc[1:3, "Units Sold"] = 5
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte           5
2     Tuesday    Espresso           5
3     Tuesday       Latte           5
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [1]:
import pandas as pd
bios = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv')
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [17]:
bios.loc[(bios['born_country']=='IND'), ['name', 'NOC']]

                      name            NOC
80          George Caridia  Great Britain
101     Algernon Kingscote  Great Britain
270            Nora Polley          India
273            Zeeshan Ali          India
274         Anand Amritraj          India
...                    ...            ...
140286       Bajrang Punia          India
140287        Deepak Punia          India
143996         Sumit Nagal          India
144114        Diksha Dagar          India
144757           Arif Khan          India

[536 rows x 2 columns]